### ISSUE TITLE
Request Postal Code

### ISSUE THREAD

**Issue by carlos-widgilabs** [avmesquita/CTT-Api#16]
Quando uso o endpoint de postalcode sempre retorna array vazio, independente de qual postalcode eu coloque. :(

**Comment by avmesquita** [comment]
Vi que acessas do Brasil.

Estás a usar código postal de Portugal?

**Comment by carlos-widgilabs** [comment]
Olá, muito obrigado por responder, sim estou usando os postal code de PT
por exemplo estou usando esse code : 1250-142  e espero este address Av. da
Liberdade 229, Lisboa, e todos os outros que eu usei o retorno é 200 mas o
response é um array vazio []. :(

**Comment by avmesquita** [comment]
Tens razão.
Pelo que vi cá, parece-me que a biblioteca de acesso mudou após a "evolução" e o legado já não é mais o mesmo.
Assim que tiver um tempo irei depurar para encontrar o que passa-se.
Obrigado por informar.

**Comment by avmesquita** [comment]
Se quiseres alterar, fique a vontade que aceito o PR.

**Comment by avmesquita** [comment]
Fixed!

**Comment by avmesquita** [comment]
De forma a ficar melhor distribuído o projeto, criei um novo projeto com a API em NestJS.
https://github.com/avmesquita/CTT-App-Angular-NestJS
